<?php

namespace PacienteBundle\Repository;

/**
 * AnalisiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalisiRepository extends \Doctrine\ORM\EntityRepository
{
}
